devices:
  # ========== 安卓设备 ==========
  # 用户1：一台安卓真机
  - user_name: "肥猪阿熊"
    phone_model: "Redmi Note 11 5G"
    platform: Android
    udid: "TC55LJMR59W8ZPRK"
    app_package: "com.cloudedge.smarteye"

  # ========== 安卓设备 ==========
  # 用户2：一台安卓模拟机
  - user_name: "肥猪"
    phone_model: "V2284A"
    platform: Android
    udid: "127.0.0.1:16384"
    app_package: "com.cloudedge.smarteye"
    wda_port: 8100  # 单设备不写也行，默认就是 8100,多设备需要手动分配

  # ========== iOS 设备 ==========
   # 用户3：一台IOS真机
  - user_name: "阿熊"
    phone_model: "iphone 14"
    platform: iOS
    udid: "00008110-000130AA1A05401E"  # 你的 iPhone UDID
    app_package: "com.meari.smartcamera" # 被测应用的 Bundle ID
    wda_port: 8100  # 单设备不写也行，默认就是 8100,多设备需要手动分配

  # ========== iOS 设备 ==========
  # 用户3：一台IOS真机
  - user_name: "阿熊"
    phone_model: "iphone 13"
    platform: iOS
    udid: "00008110-000130AA1A054029"  # 你的 iPhone UDID
    app_package: "com.meari.smartcamera" # 被测应用的 Bundle ID
    wda_port: 8101  # 单设备不写也行，默认就是 8100,多设备需要手动分配